


permalink: /:categories/:title/
paginate_path: 'page:num'
paginate:      nil

markdown:      kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
textile_ext:   textile

excerpt_separator: ""
comments: true


url:         http://webgu.github.io


links:

  - title: Articles
    url: /articles/
  - title: Blog
    url: /blog/
  - title: Category
    url: /category/

